<?php

namespace AppBundle\Repository;

/**
 * PipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipeRepository extends \Doctrine\ORM\EntityRepository
{
}
